Добавила карточку продукта
m0opy/pizza_app pull request #2
Opened 2024-07-14 14:41 UTC by m0opy

2024-07-14 14:49 UTC, IntStrFloat requested changes

2024-07-14 14:49 UTC, IntStrFloat commented on src/components/ProductCard/ProductCard.module.css
> +    color: #111719;
цвет в переменную

2024-07-14 14:49 UTC, IntStrFloat commented on src/components/ProductCard/ProductCard.props.ts
> +export interface ProductCardProps {
export interface ProductCardProps extends HTMLAttributes<HTMLElement> чтобы прокидывать свойства в карточку

2024-07-14 14:49 UTC, IntStrFloat commented on src/components/Title/Title.tsx
> +function Title({ children, className }: TitleProps) {
соблюдай единый стиль проекта, либо выносишь пропсы как { children, classname}: InterfaceProps либо props: Interface Props

2024-07-14 14:49 UTC, IntStrFloat commented on src/layout/LeftPanel/LeftPanel.module.css
> +    box-shadow: 0px 8px 40px 0px #ffc52940;
Цвет в переменную

2024-07-14 14:49 UTC, IntStrFloat commented on src/layout/LeftPanel/LeftPanel.module.css
> +    color: #9ea1b1;
Цвет в переменную

2024-07-14 14:49 UTC, IntStrFloat commented on src/layout/LeftPanel/LeftPanel.module.css
> +    box-shadow: 0px 10px 30px 0px #fe724c33;
Цвет в переменную

2024-07-14 14:49 UTC, IntStrFloat commented on src/components/Title/Title.props.ts
> +    children: string;
Разве children уже не существует у  HTMLAttributes<HTMLHeadingElement> ?

2024-07-14 14:51 UTC, m0opy commented on src/components/ProductCard/ProductCard.module.css
> +    color: #111719;
Он один раз встречается :с

2024-07-15 18:11 UTC, IntStrFloat commented
Гуд

2024-07-15 18:12 UTC, IntStrFloat approved these changes

2024-07-15 18:20 UTC, merged